---
include:
 

  - board: ergohaven
    shield: trackball
    cmake-args: -DCONFIG_ZMK_IDLE_TIMEOUT=3600000
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: ergohaven
    shield: settings_reset
